#!/bin/bash

################################################################################
# actionsbuild
#
# Copyright: (C) 2019 TechDivision GmbH - All Rights Reserved
# Author: Johann Zelger <j.zelger@techdivision.com>
################################################################################

# build bottle via brew
function build_bottle {
    FORMULA=$1
    brew install -v --build-bottle Formula/"$FORMULA".rb
    brew bottle Formula/"$FORMULA".rb --json --force-core-tap
}

# uploads the bottle to bintray
function upload_bottle {
    FORMULA=$1
    cat "$FORMULA"*.json
    FILENAME=$(cat "$FORMULA"*.json | jq --raw-output '."'"$FORMULA"'".bottle.tags."'"$OS"'".filename')
    echo "$FILENAME";
    LOCALFILE=$(cat "$FORMULA"*.json | jq --raw-output '."'"$FORMULA"'".bottle.tags."'"$OS"'".local_filename')
    echo "$LOCALFILE";
    # delete existing file due to sha256 changes
    curl -X DELETE -u"$BINTRAY_USER":"$BINTRAY_KEY" https://api.bintray.com/content/valet-sh/homebrew-core/"$FILENAME"
    curl -X DELETE -u"$BINTRAY_USER":"$BINTRAY_KEY" https://api.bintray.com/content/valet-sh/homebrew-core/"${FILENAME%.tar.gz}".json
    # upload
    curl -T "$LOCALFILE" -u"$BINTRAY_USER":"$BINTRAY_KEY" https://api.bintray.com/content/valet-sh/homebrew-core/core/core/"$FILENAME"
    curl -T "$FORMULA"*.json -u"$BINTRAY_USER":"$BINTRAY_KEY" https://api.bintray.com/content/valet-sh/homebrew-core/core/core/"${FILENAME%.tar.gz}".json
    # publish
    curl -X POST -u"$BINTRAY_USER":"$BINTRAY_KEY" https://api.bintray.com/content/valet-sh/homebrew-core/core/core/publish -d "{ \"discard\": \"false\" }"
}

# setup git config and remote
function setup_git() {
    git config --global user.email "actions@github.com"
    git config --global user.name "GitHub Actions"
    git reset --hard
    git remote set-url origin https://"${GITHUB_TOKEN}"@github.com/valet-sh/homebrew-core.git
    git checkout master
    git pull
}

# update revision by increase current revision
function update_revision {
    FORMULA=$1
    sed -i.bu "s/revision [0-9][0-9]*/revision $GITHUB_ACTION/" Formula/"$FORMULA".rb
}

# updated sha based on brew bottle build json info
function update_formula {
    FORMULA=$1
    setup_git
    SHA256=$(cat "$FORMULA"*.json | jq --raw-output '."'"$FORMULA"'".bottle.tags."'"$OS"'".sha256')
    # update sha hash
    sed -i.bu "s/sha256.*:$OS/sha256 \"$SHA256\" => :$OS/" Formula/"$FORMULA".rb 
    # update rebuild definition
    update_revision "$FORMULA"
    git add Formula/"$FORMULA".rb
    git commit --message "Actions build: $GITHUB_ACTION | Update formula $FORMULA for OS $OS"
    git push
}

# hack for brew being able to create a bottle with catalina as os
if [ "$OS" == "catalina" ]; then
    export HOMEBREW_NO_UPDATE_CLEANUP=1
    sed -i.bu 's/mojave/catalina/' /usr/local/Homebrew/Library/Homebrew/os/mac/version.rb
fi

LATEST_COMMIT_MESSAGE=$(git log -1 --pretty='%s')

# iterate all given formulas to be built
echo "${LATEST_COMMIT_MESSAGE/"[build]"/}" | sed -n 1'p' | tr ', ' '\n' | while read -r FORMULA; do
    if [[ ! -z "$FORMULA" ]]; then
        [[ -f "Formula/$FORMULA.rb" ]] && \
        update_revision "$FORMULA" && \
        build_bottle "$FORMULA" && \
        upload_bottle "$FORMULA" && \
        update_formula "$FORMULA" || \
        echo "Formula/$FORMULA.rb not found. Ignoring build"
    fi
done

